# Generated by Django 4.2.3 on 2023-08-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_taskmodel_id_alter_taskmodel_taskdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='taskDescription',
            field=models.TextField(max_length=50),
        ),
    ]
